// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using qcmAuditoriasIatf.Data;

#nullable disable

namespace qcmAuditoriasIatf.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260127202421_AddProcesoUnidadLinea")]
    partial class AddProcesoUnidadLinea
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Auditorias.Auditoria", b =>
                {
                    b.Property<int>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditoriaId"));

                    b.Property<string>("Alcance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditorLiderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAuditoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditoriaId");

                    b.ToTable("qmcAudAuditoria");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Auditorias.AuditoriaChecklist", b =>
                {
                    b.Property<int>("AuditoriaChecklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditoriaChecklistId"));

                    b.Property<string>("AuditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AuditoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cumple")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("int");

                    b.HasKey("AuditoriaChecklistId");

                    b.HasIndex("AuditoriaId");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("ProcesoId");

                    b.ToTable("qmcAudAuditoriaChecklist");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Auditorias.AuditoriaProceso", b =>
                {
                    b.Property<int>("AuditoriaProcesoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditoriaProcesoId"));

                    b.Property<string>("AuditorAsignadoId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AuditoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Linea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("int");

                    b.Property<string>("UnidadNegocio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditoriaProcesoId");

                    b.HasIndex("AuditoriaId");

                    b.HasIndex("ProcesoId");

                    b.ToTable("qmcAudAuditoriaProceso");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Catalogos.ChecklistPregunta", b =>
                {
                    b.Property<int>("PreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreguntaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("ClausulaId")
                        .HasColumnType("int");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("int");

                    b.Property<string>("Requisito")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PreguntaId");

                    b.HasIndex("ClausulaId");

                    b.HasIndex("ProcesoId");

                    b.ToTable("qmcAudChecklistPregunta");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Catalogos.ClausulaIATF", b =>
                {
                    b.Property<int>("ClausulaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClausulaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClausulaId");

                    b.ToTable("qmcAudClausulaIATF");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Catalogos.Proceso", b =>
                {
                    b.Property<int>("ProcesoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcesoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineaNombre")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnidadNegocio")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ProcesoId");

                    b.ToTable("qmcAudProceso");

                    b.HasData(
                        new
                        {
                            ProcesoId = 1,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-0100-D1",
                            Nombre = "ALTA DIRECCIÓN"
                        },
                        new
                        {
                            ProcesoId = 2,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-6100-D1",
                            Nombre = "AUDITORIAS INTERNAS"
                        },
                        new
                        {
                            ProcesoId = 3,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-6700-D1",
                            Nombre = "SATISFACCIÓN AL CLIENTE / QUEJAS DEL CLIENTE"
                        },
                        new
                        {
                            ProcesoId = 4,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-6600-D1",
                            Nombre = "NO CONFORMIDADES, ACCIONES CORRECTIVAS Y PREVENTIVAS"
                        },
                        new
                        {
                            ProcesoId = 5,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-3000-D1",
                            Nombre = "VENTAS"
                        },
                        new
                        {
                            ProcesoId = 6,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-6200-D1",
                            Nombre = "APQP"
                        },
                        new
                        {
                            ProcesoId = 7,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-7100-D1",
                            Nombre = "PLANEACIÓN DE LA PRODUCCIÓN"
                        },
                        new
                        {
                            ProcesoId = 8,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-4000-D1",
                            Nombre = "COMPRAS / SELECCIÓN Y DESARROLLO DE PROVEEDORES"
                        },
                        new
                        {
                            ProcesoId = 9,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-9000-D1",
                            Nombre = "RECIBO, ALMACENAJE, SURTIMIENTO, PRODUCTO TERMINADO Y EMBARQUES"
                        },
                        new
                        {
                            ProcesoId = 10,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-6000-D1",
                            Nombre = "CALIDAD PROCESO"
                        },
                        new
                        {
                            ProcesoId = 11,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-7000-D1",
                            Nombre = "PRODUCCIÓN"
                        },
                        new
                        {
                            ProcesoId = 12,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-8000-D1",
                            Nombre = "INGENIERIA"
                        },
                        new
                        {
                            ProcesoId = 13,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-6300-D1",
                            Nombre = "CALIDAD PROVEEDORES"
                        },
                        new
                        {
                            ProcesoId = 14,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-6500-D1",
                            Nombre = "GESTION DE CAMBIOS"
                        },
                        new
                        {
                            ProcesoId = 15,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-1000-D1",
                            Nombre = "RECURSOS HUMANOS Y MOTIVACIÓN DEL PERSONAL"
                        },
                        new
                        {
                            ProcesoId = 16,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-1300-D1",
                            Nombre = "ENTRENAMIENTO"
                        },
                        new
                        {
                            ProcesoId = 17,
                            Activo = true,
                            Area = "",
                            Codigo = "MX-6400-D1",
                            Nombre = "CONTROL DE EQUIPOS E INSTRUMENTOS DE MEDICIÓN"
                        });
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Catalogos.TipoHallazgo", b =>
                {
                    b.Property<int>("TipoHallazgoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoHallazgoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severidad")
                        .HasColumnType("int");

                    b.HasKey("TipoHallazgoId");

                    b.ToTable("qmcAudTipoHallazgo");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Evidencias.Evidencia", b =>
                {
                    b.Property<int>("EvidenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvidenciaId"));

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReferenciaId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenciaTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvidenciaId");

                    b.ToTable("qmcAudEvidencia");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Evidencias.HistorialCambio", b =>
                {
                    b.Property<int>("HistorialCambioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialCambioId"));

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HistorialCambioId");

                    b.ToTable("qmcAudHistorialCambio");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Hallazgos.AccionCorrectiva", b =>
                {
                    b.Property<int>("AccionCorrectivaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccionCorrectivaId"));

                    b.Property<string>("AccionDefinida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalisisCausa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Eficaz")
                        .HasColumnType("bit");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenciaImplementacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaImplementacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("HallazgoId")
                        .HasColumnType("int");

                    b.Property<string>("ResponsableId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccionCorrectivaId");

                    b.HasIndex("HallazgoId");

                    b.ToTable("qmcAudAccionCorrectiva");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Hallazgos.Hallazgo", b =>
                {
                    b.Property<int>("HallazgoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HallazgoId"));

                    b.Property<int>("AuditoriaId")
                        .HasColumnType("int");

                    b.Property<int>("ClausulaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCompromiso")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("int");

                    b.Property<string>("ResponsableId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoHallazgoId")
                        .HasColumnType("int");

                    b.HasKey("HallazgoId");

                    b.HasIndex("AuditoriaId");

                    b.HasIndex("ClausulaId");

                    b.HasIndex("ProcesoId");

                    b.HasIndex("TipoHallazgoId");

                    b.ToTable("qmcAudHallazgo");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Auditorias.AuditoriaChecklist", b =>
                {
                    b.HasOne("qcmAuditoriasIatf.Models.Auditorias.Auditoria", "Auditoria")
                        .WithMany("AuditoriaChecklists")
                        .HasForeignKey("AuditoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("qcmAuditoriasIatf.Models.Catalogos.ChecklistPregunta", "Pregunta")
                        .WithMany("AuditoriaChecklists")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("qcmAuditoriasIatf.Models.Catalogos.Proceso", "Proceso")
                        .WithMany()
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auditoria");

                    b.Navigation("Pregunta");

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Auditorias.AuditoriaProceso", b =>
                {
                    b.HasOne("qcmAuditoriasIatf.Models.Auditorias.Auditoria", "Auditoria")
                        .WithMany("AuditoriaProcesos")
                        .HasForeignKey("AuditoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("qcmAuditoriasIatf.Models.Catalogos.Proceso", "Proceso")
                        .WithMany("AuditoriaProcesos")
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auditoria");

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Catalogos.ChecklistPregunta", b =>
                {
                    b.HasOne("qcmAuditoriasIatf.Models.Catalogos.ClausulaIATF", "Clausula")
                        .WithMany("ChecklistPreguntas")
                        .HasForeignKey("ClausulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("qcmAuditoriasIatf.Models.Catalogos.Proceso", "Proceso")
                        .WithMany()
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clausula");

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Hallazgos.AccionCorrectiva", b =>
                {
                    b.HasOne("qcmAuditoriasIatf.Models.Hallazgos.Hallazgo", "Hallazgo")
                        .WithMany("AccionesCorrectivas")
                        .HasForeignKey("HallazgoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hallazgo");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Hallazgos.Hallazgo", b =>
                {
                    b.HasOne("qcmAuditoriasIatf.Models.Auditorias.Auditoria", "Auditoria")
                        .WithMany("Hallazgos")
                        .HasForeignKey("AuditoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("qcmAuditoriasIatf.Models.Catalogos.ClausulaIATF", "Clausula")
                        .WithMany()
                        .HasForeignKey("ClausulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("qcmAuditoriasIatf.Models.Catalogos.Proceso", "Proceso")
                        .WithMany()
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("qcmAuditoriasIatf.Models.Catalogos.TipoHallazgo", "TipoHallazgo")
                        .WithMany("Hallazgos")
                        .HasForeignKey("TipoHallazgoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auditoria");

                    b.Navigation("Clausula");

                    b.Navigation("Proceso");

                    b.Navigation("TipoHallazgo");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Auditorias.Auditoria", b =>
                {
                    b.Navigation("AuditoriaChecklists");

                    b.Navigation("AuditoriaProcesos");

                    b.Navigation("Hallazgos");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Catalogos.ChecklistPregunta", b =>
                {
                    b.Navigation("AuditoriaChecklists");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Catalogos.ClausulaIATF", b =>
                {
                    b.Navigation("ChecklistPreguntas");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Catalogos.Proceso", b =>
                {
                    b.Navigation("AuditoriaProcesos");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Catalogos.TipoHallazgo", b =>
                {
                    b.Navigation("Hallazgos");
                });

            modelBuilder.Entity("qcmAuditoriasIatf.Models.Hallazgos.Hallazgo", b =>
                {
                    b.Navigation("AccionesCorrectivas");
                });
#pragma warning restore 612, 618
        }
    }
}
